### ISSUE TITLE
How can i halt the UR5 with this demo

### ISSUE THREAD

**Issue by Jerrrrry-Zhu** [gouxiangchen/UR5-control-with-RG2#3]
hi，could you tell me how to use this demo to halt the ur5，i do not find a function in this demo to halt the UR5

**Comment by gouxiangchen** [comment]
There are some functions in URScript which can stop the robot, "stopj" or "stopl" may be useful. You can send these scripts to UR via socket just like the moving operations in my code.

The description of stopj and stopl can be find in official URScript manual document.
